version: '3.1'
services:
 app:  
  build:
   context: .
   dockerfile: Dockerfile
  container_name: vuetify_kanban
  ports:
   - "3000:80"
  #deploy:
  # replicas: 3
  networks:
   - fe

 nginx:
  image: nginx:alpine
  ports:
   - "80:80"
  volumes:
   - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  depends_on:
   - app
  networks:
   - fe

networks:
 fe:

